run:
	g++ -std=c++0x HeapFileManager.cpp ../core/TableMetadata.pb.cc ../core/MetaDataProvider.cpp ../common/InfoPool.cpp ../common/Utils.cpp Page.cpp -g3 -Wall -lprotobuf -DTEST_HFM -DDEBUG -o test_hfm
	./test_hfm